# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 801
data_root: /data/users/zhengzhiyu/SSL/dataset/cityscapes/
# arguments for training
epochs: 240
batch_size: 1 # per GPU x 2 GPUs
lr: 0.005
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0
amp: True

img_scales: [0.25, 0.5, 1.5, 2.0]
feat_s_scales: [0.75]
feat_l_scales: [1.25]
warm_up: 10
# arguments for model
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]



