# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 513
data_root: /data1/users/zhengzhiyu/ssl_workplace/dataset/VOC2012/

# arguments for training
epochs: 80
batch_size: 2 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
amp: True


# arguments for scale factors

img_scales: [0.25, 0.5, 1.5, 2.0]

# feat_s_scales: [0.75, 1.0]
# feat_l_scales: [1.0, 1.25]

feat_s_scales: [0.75]
feat_l_scales: [1.25]

warm_up: 0
# arguments for model
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]